version: '3.8'

services:
  # 1. Base de Datos Relacional (Usuarios, Tracks, Metadata)
  postgres:
    image: postgres:15-alpine
    container_name: super_app_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: streaming_db
    ports:
      - "5435:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # 2. Base de Datos Vectorial (Para el Motor de Recomendación - Req 1.3)
  qdrant:
    image: qdrant/qdrant
    container_name: super_app_qdrant
    restart: always
    ports:
      - "6333:6333" # Puerto para API HTTP
      - "6334:6334" # Puerto para GRPC
    volumes:
      - ./qdrant_data:/qdrant/storage

  # (Opcional) Interfaz gráfica para ver la Base de Datos Postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: super_app_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres